/**
 * Game Registry Generator
 *
 * Scans the src/games/ directory and generates src/game-registry.generated.ts
 * which contains lazy-loaded imports and metadata for every game.
 *
 * Usage: pnpm generate-registry
 *
 * This script:
 * 1. Reads all subdirectories of src/games/
 * 2. For each directory, checks for an index.ts file
 * 3. Validates it exports a PlayBoxGame-compatible object
 * 4. Generates a registry file with lazy imports
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const GAMES_DIR = path.resolve(__dirname, '../src/games');
const OUTPUT_FILE = path.resolve(__dirname, '../src/game-registry.generated.ts');

interface GameDir {
  id: string;
  path: string;
  hasIndex: boolean;
}

function scanGamesDir(): GameDir[] {
  if (!fs.existsSync(GAMES_DIR)) {
    console.log('No games directory found. Creating empty registry.');
    return [];
  }

  const entries = fs.readdirSync(GAMES_DIR, { withFileTypes: true });
  const games: GameDir[] = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      const indexPath = path.join(GAMES_DIR, entry.name, 'index.ts');
      games.push({
        id: entry.name,
        path: entry.name,
        hasIndex: fs.existsSync(indexPath),
      });
    }
  }

  return games;
}

function generateRegistry(games: GameDir[]): string {
  const validGames = games.filter((g) => g.hasIndex);

  if (validGames.length === 0) {
    return `/**
 * AUTO-GENERATED by scripts/generate-game-registry.ts
 * DO NOT EDIT MANUALLY — changes will be overwritten.
 *
 * Generated at: ${new Date().toISOString()}
 *
 * No games found in src/games/. Add game directories with index.ts files.
 */

import type { GameRegistry } from '@/types/game';

export const gameRegistry: GameRegistry = {};

export const gameMetas: Record<string, import('@/types/game').GameMetadata> = {};
`;
  }

  const imports = validGames
    .map(
      (g) =>
        `const ${camelCase(g.id)} = () => import('@/games/${g.id}/index');`,
    )
    .join('\n');

  const registryEntries = validGames
    .map(
      (g) =>
        `  '${g.id}': {
    metadata: ${camelCase(g.id + '_meta')} ,
    load: ${camelCase(g.id)},
  },`,
    )
    .join('\n');

  const metaImports = validGames
    .map(
      (g) =>
        `import { metadata as ${camelCase(g.id + '_meta')} } from '@/games/${g.id}/index';`,
    )
    .join('\n');

  return `/**
 * AUTO-GENERATED by scripts/generate-game-registry.ts
 * DO NOT EDIT MANUALLY — changes will be overwritten.
 *
 * Generated at: ${new Date().toISOString()}
 * Games found: ${validGames.length}
 */

import type { GameRegistry } from '@/types/game';

// Static metadata imports (no game code loaded)
${metaImports}

// Lazy load functions (game code + engine chunks loaded on demand)
${imports}

export const gameRegistry: GameRegistry = {
${registryEntries}
};
`;
}

function camelCase(str: string): string {
  return str
    .replace(/[-_](\w)/g, (_, c) => c.toUpperCase())
    .replace(/^(\w)/, (_, c) => c.toLowerCase());
}

function main() {
  console.log('🔍 Scanning src/games/ for game directories...');
  const games = scanGamesDir();

  console.log(`📦 Found ${games.length} game directory(ies):`);
  for (const game of games) {
    const status = game.hasIndex ? '✅' : '⚠️  (missing index.ts)';
    console.log(`   ${game.id} ${status}`);
  }

  const output = generateRegistry(games);
  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');

  console.log(`\n✅ Generated registry at src/game-registry.generated.ts`);
  console.log(`   ${games.filter((g) => g.hasIndex).length} game(s) registered`);
}

main();
