/**
 * AUTO-GENERATED by scripts/generate-game-registry.ts
 * DO NOT EDIT MANUALLY — changes will be overwritten.
 *
 * Registered games: sudoku, snake, breakout
 */

import type { GameRegistry, GameMetadata, GameCategory, EngineType, Difficulty } from '@/types/game';

// ---- Sudoku Metadata ----
const sudokuMeta: GameMetadata = {
  id: 'sudoku',
  name: 'Sudoku',
  description: 'Fill the grid with numbers — no repeats in any row, column, or box!',
  longDescription:
    'Place numbers 1 through N in the grid so that each row, column, and box contains every number exactly once. Tap a cell, then tap a number to fill it in. Use pencil mode to note candidates, and hints if you get stuck!',
  category: 'logic-puzzle' as GameCategory,
  engine: 'canvas' as EngineType,
  difficulties: ['easy', 'medium', 'hard'] as Difficulty[],
  defaultDifficulty: 'easy' as Difficulty,
  tags: ['sudoku', 'puzzle', 'logic', 'numbers', 'grid', 'brain', 'thinking'],
  thumbnail: '/games/sudoku/thumbnail.png',
  assetsPath: '/games/sudoku/',
  supportsKeyboard: true,
  supportsTouch: true,
  supportsGamepad: false,
  minWidth: 320,
  version: '1.0.0',
  author: 'PlayBox',
};

// ---- Snake Metadata ----
const snakeMeta: GameMetadata = {
  id: 'snake',
  name: 'Snake',
  description: "Guide the snake to eat food and grow longer — don't hit the walls or yourself!",
  longDescription:
    'Use arrow keys or WASD to steer the snake. On mobile, swipe in any direction or use the on-screen D-pad. Eat the red apple to grow longer. Avoid crashing into walls (or wrap around on Easy!) and your own tail. How long can you get?',
  category: 'arcade' as GameCategory,
  engine: 'kaboom' as EngineType,
  difficulties: ['easy', 'medium', 'hard'] as Difficulty[],
  defaultDifficulty: 'medium' as Difficulty,
  tags: ['snake', 'arcade', 'classic', 'retro', 'growing', 'food'],
  thumbnail: '/games/snake/thumbnail.png',
  assetsPath: '/games/snake/',
  supportsKeyboard: true,
  supportsTouch: true,
  supportsGamepad: false,
  minWidth: 320,
  version: '1.0.0',
  author: 'PlayBox',
};

// ---- Breakout Metadata ----
const breakoutMeta: GameMetadata = {
  id: 'breakout',
  name: 'Breakout',
  description: "Bounce the ball to break all the bricks — don't let it fall!",
  longDescription:
    'Move the paddle left and right to bounce the ball upward. Break all the colorful bricks to win! Different colored bricks are worth different points. You have multiple lives, but if the ball falls below the paddle, you lose one. Click or tap to launch the ball.',
  category: 'arcade' as GameCategory,
  engine: 'kaboom' as EngineType,
  difficulties: ['easy', 'medium', 'hard'] as Difficulty[],
  defaultDifficulty: 'medium' as Difficulty,
  tags: ['breakout', 'arcade', 'classic', 'bricks', 'paddle', 'ball', 'retro'],
  thumbnail: '/games/breakout/thumbnail.png',
  assetsPath: '/games/breakout/',
  supportsKeyboard: true,
  supportsTouch: true,
  supportsGamepad: false,
  minWidth: 320,
  version: '1.0.0',
  author: 'PlayBox',
};

// ---- Game Registry ----
export const gameRegistry: GameRegistry = {
  sudoku: {
    metadata: sudokuMeta,
    load: () => import('@/games/sudoku/index'),
  },
  snake: {
    metadata: snakeMeta,
    load: () => import('@/games/snake/index'),
  },
  breakout: {
    metadata: breakoutMeta,
    load: () => import('@/games/breakout/index'),
  },
};

// ---- Game Metas (convenience) ----
export const gameMetas: Record<string, GameMetadata> = {
  sudoku: sudokuMeta,
  snake: snakeMeta,
  breakout: breakoutMeta,
};
