/**
 * AUTO-GENERATED by scripts/generate-game-registry.ts
 * DO NOT EDIT MANUALLY — changes will be overwritten.
 *
 * No games found in src/games/. Add game directories with index.ts files.
 *
 * This is a placeholder registry that will be replaced when games are added.
 */

import type { GameRegistry } from '@/types/game';

export const gameRegistry: GameRegistry = {};

export const gameMetas: Record<string, import('@/types/game').GameMetadata> = {};
